runtime: nodejs18

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /favicon.png
  static_files: frontend/favicon.png
  upload: frontend/favicon.png

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto